### ISSUE TITLE
希望官方能出air001的arduino看门狗库

### ISSUE THREAD

**Issue by godcjiajia** [Air-duino/Arduino-AirMCU#17]
## 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
希望官方能出air001的arduino看门狗库

## 描述您想要的解决方案 / Describe the solution you'd like
希望官方能出air001的arduino看门狗库

## 描述您考虑过的替代方案 / Describe alternatives you've considered
无

## 其他备注信息
对于这种成本敏感的芯片, 功能要求不多, 但是稳定性不能差了, 所以就差个看门狗就能量产产品了

**Comment by santook** [comment]
代码如下，希望作者能封装进下一次的包中。
`#pragma once

typedef struct
{
	uint32_t Prescaler;  /*!< Select the prescaler of the IWDG.
							  This parameter can be a value of @ref IWDG_Prescaler */

	uint32_t Reload;     /*!< Specifies the IWDG down-counter reload value.
							  This parameter must be a number between Min_Data = 0 and Max_Data = 0x0FFF */

} IWDG_InitTypeDef;

/**
  * @brief  IWDG Handle Structure definition
  */
typedef struct
{
	IWDG_TypeDef* Instance;  /*!< Register base address    */

	IWDG_InitTypeDef             Init;       /*!< IWDG required parameters */

} IWDG_HandleTypeDef;

#define HAL_IWDG_DEFAULT_TIMEOUT            48U

/**
  * @}
  */

  /* Exported constants --------------------------------------------------------*/
  /** @defgroup IWDG_Exported_Constants IWDG Exported Constants
	* @{
	*/

	/** @defgroup IWDG_Prescaler IWDG Prescaler
	  * @{
	  */
#define IWDG_PRESCALER_4                0x00000000U                   /*!< IWDG prescaler set to 4   */
#define IWDG_PRESCALER_8                IWDG_PR_PR_0                  /*!< IWDG prescaler set to 8   */
#define IWDG_PRESCALER_16               IWDG_PR_PR_1                  /*!< IWDG prescaler set to 16  */
#define IWDG_PRESCALER_32               (IWDG_PR_PR_1 | IWDG_PR_PR_0) /*!< IWDG prescaler set to 32  */
#define IWDG_PRESCALER_64               IWDG_PR_PR_2                  /*!< IWDG prescaler set to 64  */
#define IWDG_PRESCALER_128              (IWDG_PR_PR_2 | IWDG_PR_PR_0) /*!< IWDG prescaler set to 128 */
#define IWDG_PRESCALER_256              (IWDG_PR_PR_2 | IWDG_PR_PR_1) /*!< IWDG prescaler set to 256 */
	  /**
		* @}
		*/

		/**
		  * @}
		  */


		  /* Exported macros -----------------------------------------------------------*/
		  /** @defgroup IWDG_Exported_Macros IWDG Exported Macros
			* @{
			*/

			/**
			  * @brief  Enable the IWDG peripheral.
			  * @param  __HANDLE__  IWDG handle
			  * @retval None
			  */
#define __HAL_IWDG_START(__HANDLE__)                WRITE_REG((__HANDLE__)->Instance->KR, IWDG_KEY_ENABLE)

			  /**
				* @brief  Reload IWDG counter with value defined in the reload register
				*         (write access to IWDG_PR & IWDG_RLR registers disabled).
				* @param  __HANDLE__  IWDG handle
				* @retval None
				*/
#define __HAL_IWDG_RELOAD_COUNTER(__HANDLE__)       WRITE_REG((__HANDLE__)->Instance->KR, IWDG_KEY_RELOAD)

				/* Exported functions --------------------------------------------------------*/
				/** @defgroup IWDG_Exported_Functions  IWDG Exported Functions
				  * @{
				  */

				  /** @defgroup IWDG_Exported_Functions_Group1 Initialization and Start functions
					* @{
					*/
					/* Initialization/Start functions  ********************************************/
HAL_StatusTypeDef HAL_IWDG_Init(IWDG_HandleTypeDef* hiwdg);
/**
  * @}
  */

  /** @defgroup IWDG_Exported_Functions_Group2 IO operation functions
	* @{
	*/
	/* I/O operation functions ****************************************************/
HAL_StatusTypeDef HAL_IWDG_Refresh(IWDG_HandleTypeDef* hiwdg);
/**
  * @}
  */

  /**
	* @}
	*/

	/* Private constants ---------------------------------------------------------*/
	/** @defgroup IWDG_Private_Constants IWDG Private Constants
	  * @{
	  */

	  /**
		* @brief  IWDG Key Register BitMask
		*/
#define IWDG_KEY_RELOAD                 0x0000AAAAU  /*!< IWDG Reload Counter Enable   */
#define IWDG_KEY_ENABLE                 0x0000CCCCU  /*!< IWDG Peripheral Enable       */
#define IWDG_KEY_WRITE_ACCESS_ENABLE    0x00005555U  /*!< IWDG KR Write Access Enable  */
#define IWDG_KEY_WRITE_ACCESS_DISABLE   0x00000000U  /*!< IWDG KR Write Access Disable */

		/**
		  * @}
		  */

		  /* Private macros ------------------------------------------------------------*/
		  /** @defgroup IWDG_Private_Macros IWDG Private Macros
			* @{
			*/

			/**
			  * @brief  Enable write access to IWDG_PR and IWDG_RLR registers.
			  * @param  __HANDLE__  IWDG handle
			  * @retval None
			  */
#define IWDG_ENABLE_WRITE_ACCESS(__HANDLE__)  WRITE_REG((__HANDLE__)->Instance->KR, IWDG_KEY_WRITE_ACCESS_ENABLE)

			  /**
				* @brief  Disable write access to IWDG_PR and IWDG_RLR registers.
				* @param  __HANDLE__  IWDG handle
				* @retval None
				*/
#define IWDG_DISABLE_WRITE_ACCESS(__HANDLE__) WRITE_REG((__HANDLE__)->Instance->KR, IWDG_KEY_WRITE_ACCESS_DISABLE)

				/**
				  * @brief  Check IWDG prescaler value.
				  * @param  __PRESCALER__  IWDG prescaler value
				  * @retval None
				  */
#define IS_IWDG_PRESCALER(__PRESCALER__)      (((__PRESCALER__) == IWDG_PRESCALER_4)  || \
                                               ((__PRESCALER__) == IWDG_PRESCALER_8)  || \
                                               ((__PRESCALER__) == IWDG_PRESCALER_16) || \
                                               ((__PRESCALER__) == IWDG_PRESCALER_32) || \
                                               ((__PRESCALER__) == IWDG_PRESCALER_64) || \
                                               ((__PRESCALER__) == IWDG_PRESCALER_128)|| \
                                               ((__PRESCALER__) == IWDG_PRESCALER_256))

				  /**
					* @brief  Check IWDG reload value.
					* @param  __RELOAD__  IWDG reload value
					* @retval None
					*/
#define IS_IWDG_RELOAD(__RELOAD__)            ((__RELOAD__) <= IWDG_RLR_RL)

					/**
					  * @}
					  */

					  /**
						* @}
						*/

						/**
						  * @}
						  */



HAL_StatusTypeDef HAL_IWDG_Init(IWDG_HandleTypeDef* hiwdg)
{
	uint32_t tickstart;

	/* Check the IWDG handle allocation */
	if (hiwdg == NULL)
	{
		return HAL_ERROR;
	}

	/* Check the parameters */
	assert_param(IS_IWDG_ALL_INSTANCE(hiwdg->Instance));
	assert_param(IS_IWDG_PRESCALER(hiwdg->Init.Prescaler));
	assert_param(IS_IWDG_RELOAD(hiwdg->Init.Reload));

	/* Enable IWDG. LSI requires ready */
	__HAL_IWDG_START(hiwdg);

	/* Enable write access to IWDG_PR and IWDG_RLR registers by writing 0x5555 in KR */
	IWDG_ENABLE_WRITE_ACCESS(hiwdg);

	/* Write to IWDG registers the Prescaler & Reload values to work with */
	hiwdg->Instance->PR = hiwdg->Init.Prescaler;
	hiwdg->Instance->RLR = hiwdg->Init.Reload;

	/* Check pending flag, if previous update not done, return timeout */
	tickstart = HAL_GetTick();

	/* Wait for register to be updated */
	while (hiwdg->Instance->SR != RESET)
	{
		if ((HAL_GetTick() - tickstart) > HAL_IWDG_DEFAULT_TIMEOUT)
		{
			return HAL_TIMEOUT;
		}
	}
	/* Reload IWDG counter with value defined in the reload register */
	__HAL_IWDG_RELOAD_COUNTER(hiwdg);

	/* Return function status */
	return HAL_OK;
}

/**
  * @}
  */

  /** @addtogroup IWDG_Exported_Functions_Group2
	*  @brief   IO operation functions
	*
  @verbatim
   ===============================================================================
						##### IO operation functions #####
   ===============================================================================
   [..]  This section provides functions allowing to:
		(+) Refresh the IWDG.

  @endverbatim
	* @{
	*/

	/**
	  * @brief  Refresh the IWDG.
	  * @param  hiwdg  pointer to a IWDG_HandleTypeDef structure that contains
	  *                the configuration information for the specified IWDG module.
	  * @retval HAL status
	  */
HAL_StatusTypeDef HAL_IWDG_Refresh(IWDG_HandleTypeDef* hiwdg)
{
	/* Reload IWDG counter with value defined in the reload register */
	__HAL_IWDG_RELOAD_COUNTER(hiwdg);

	/* Return function status */
	return HAL_OK;
}

class WatchDogTimer
{
public:
	/*
	初始化
	Prescaler - 分频参数,IWDG_PRESCALER_8到IWDG_PRESCALER_256
	Reload - 重装载值（溢出值）
	IWDT的时钟来源为32768时钟，当32分频时，时基为1ms。
	*/
	bool Begin(uint32_t Prescaler, uint32_t Reload);
	/*
	喂狗
	*/
	void Feed();
private:
	IWDG_HandleTypeDef   IwdgHandle;
};

bool WatchDogTimer::Begin(uint32_t Prescaler, uint32_t Reload)
{
	bool ret = true;
	IwdgHandle.Instance = IWDG;                     /* 选择IWDG */
	IwdgHandle.Init.Prescaler = Prescaler;  /* 配置32分频 */
	IwdgHandle.Init.Reload = Reload;                /* IWDG计数器重装载值为1000，1s */
	if (HAL_IWDG_Init(&IwdgHandle) != HAL_OK)
	{
		ret = false;
	}
	return ret;
}

void WatchDogTimer::Feed()
{
	HAL_IWDG_Refresh(&IwdgHandle);
}
`
