### ISSUE TITLE
整形全局变量无法使用超过373个

### ISSUE THREAD

**Issue by zwguan** [Air-duino/Arduino-AirMCU#21]
## 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
程序中需要使用一个数组用于作为modbus的寄存器，发现全局变量一旦>=373个程序就无法编译，air001手册介绍SRAM有4kb，是否可以扩展一下全局变量的数量？

## 描述您想要的解决方案 / Describe the solution you'd like
适当增加全局变量的数量

**Comment by chenxuuu** [comment]
issue类型新建错了吧？

**Comment by zwguan** [comment]
> issue类型新建错了吧？

第一次来这里，还不太熟悉怎么操作，主要是英语页不太好^v^
