### ISSUE TITLE
希望Air001 Arduino下增加低功耗支持

### ISSUE THREAD

**Issue by Deerczl** [Air-duino/Arduino-AirMCU#22]
## 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.
增加低功耗支持以满足高性价比产品的需要
## 描述您想要的解决方案 / Describe the solution you'd like
将HAL库中CMSIS的WFI、WFE函数与HAL_PWR封装至Arduino库中。
## 描述您考虑过的替代方案 / Describe alternatives you've considered
None
## 其他备注信息
查询到HAL下有HAL_PWR对sleep和stop状态提供了支持。但其函数内部所引用的WFI、WFE函数在Cortex CMSIS的头文件中，不明白如何添加至Arduino引用。因此希望可以提供帮助或将该功能打包进Arduino pkg中。先行致谢。

**Comment by HalfSweet** [comment]
不需要单独打包，直接使用对应的HAL/LL函数即可
