### ISSUE TITLE
串口的重定向不符合直觉

### ISSUE THREAD

**Issue by cxeo** [Air-duino/Arduino-AirMCU#30]
### 描述一下这个bug / Describe the bug

使用Serial2.begin(9600);初始化

通过Serial2.write(data[i]);，实际信号是从PA2（USART1_TX）输出，并不是PA0（USART2_TX）

### 复现步骤 / To Reproduce

随便就能复现，不管是用Serial2.write还是Serial.write都是从PA2输出

### 预期的行为 / Expected behavior

修复

### 截图 / Screenshots

无

### 日志 / Logs

无

### 系统 / System

Win10

### 软件版本 / Version

Arduino IDE 2.1.0

### 验证

- [X] 检查该问题是否已被提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by HalfSweet** [comment]
实际Serial2被重定向到了Serial，是当初的设计失误，会尽快修复
如果想用另一个串口，可以手动实例化 `Serial1`
```cpp
HardwareSerial Serial1(RXPIN, TXPIN);
```
