### ISSUE TITLE
用户名带中文链接会失败

### ISSUE THREAD

**Issue by HalfSweet** [Air-duino/Arduino-AirMCU#31]
### 描述一下这个bug / Describe the bug

如果用户名中含有中文，链接器将会报错

### 复现步骤 / To Reproduce

如果用户名中含有中文，链接器将会报错

### 预期的行为 / Expected behavior

应该正常工作

### 日志 / Logs

collect2.exe: error: ld returned 1 exit status

### 系统 / System

Win10

### 软件版本 / Version

0.3.3

### 验证

- [X] 检查该问题是否已被提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by chenxuuu** [comment]
https://arduino.luatos.com/FAQ/chinese_path.html
