### ISSUE TITLE
希望官方能不arduino移植到PlatformIO平台

### ISSUE THREAD

**Issue by ls701110** [Air-duino/Arduino-AirMCU#36]
### 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.

arduino原生编译器体验太差了，希望移植到PlatformIO使用vscode进行开发

### 描述您想要的解决方案 / Describe the solution you'd like

arduino原生编译器体验太差了，希望移植到PlatformIO使用vscode进行开发

### 描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way

arduino原生编译器体验太差了，希望移植到PlatformIO使用vscode进行开发

### 其他备注信息或截图 / Add any other context or screenshots about the feature request here

arduino原生编译器体验太差了，希望移植到PlatformIO使用vscode进行开发

**Comment by chenxuuu** [comment]
#4
