### ISSUE TITLE
I2C master requestFrom 异常堵塞

### ISSUE THREAD

**Issue by createskyblue** [Air-duino/Arduino-AirMCU#51]
### 描述一下这个bug / Describe the bug

Wire库中
uint8_t requestFrom(uint8_t address, uint8_t quantity)
当参数quantity大于1时，发生堵塞，其中逻辑分析仪抓取波形如下
![image](https://github.com/Air-duino/Arduino-AirMCU/assets/20317561/dfa2d2cf-23b6-4f19-88eb-347257828e08)
经过简单的打印调试，定位到堵塞在下面红框的代码段中
![image](https://github.com/Air-duino/Arduino-AirMCU/assets/20317561/a05a8839-c0ce-40d4-a23b-ba4f23f8f374)

### 复现步骤 / To Reproduce

```
uint32_t data = 0;
  _wire->beginTransmission(_i2caddr);
  _wire->write(reg);
  _wire->endTransmission();
  _wire->requestFrom(_i2caddr, 3);
  data = _wire->read();
  data <<= 8;
  data |= _wire->read();
  data <<= 8;
  data |= _wire->read();
  return data;
```
```
i2c_status_e i2c_master_read(i2c_t *obj, uint8_t dev_address, uint8_t *data, uint16_t size)
{
  i2c_status_e ret = I2C_OK;
  uint32_t tickstart = HAL_GetTick();
  uint32_t delta = 0;
  uint32_t err = 0;
  HAL_StatusTypeDef status = HAL_OK;

  putchar('.');

#if defined(I2C_OTHER_FRAME)
  uint32_t XferOptions = obj->handle.XferOptions; // save XferOptions value, because handle can be modified by HAL, which cause issue in case of NACK from slave
#endif
  do {
#if defined(I2C_OTHER_FRAME)
putchar('!');
    status = HAL_I2C_Master_Seq_Receive_IT(&(obj->handle), dev_address, data, size, XferOptions);
#else
putchar('@');
    status = HAL_I2C_Master_Receive_IT(&(obj->handle), dev_address, data, size);
#endif
putchar('#');
    // Ensure i2c ready
    if (status == HAL_BUSY) {
      delta = (HAL_GetTick() - tickstart);
      if (delta > I2C_TIMEOUT_TICK) {
        ret = I2C_BUSY;
        putchar('E');
        break;
      }
    } else {
      ret = (status == HAL_OK) ? I2C_OK : I2C_ERROR;
    }
    
  putchar('1');
  } while (status == HAL_BUSY);

  if (ret == I2C_OK) {
    putchar('2');
    tickstart = HAL_GetTick();
    // wait for transfer completion
    while ((HAL_I2C_GetState(&(obj->handle)) != HAL_I2C_STATE_READY) && (delta < I2C_TIMEOUT_TICK)) {
      delta = (HAL_GetTick() - tickstart);
      if (HAL_I2C_GetError(&(obj->handle)) != HAL_I2C_ERROR_NONE) {
        break;
      }
      
    }

    err = HAL_I2C_GetError(&(obj->handle));
    if ((delta >= I2C_TIMEOUT_TICK)
        || ((err & HAL_I2C_ERROR_TIMEOUT) == HAL_I2C_ERROR_TIMEOUT)) {
      ret = I2C_TIMEOUT;
    } else {
      if ((err & HAL_I2C_ERROR_AF) == HAL_I2C_ERROR_AF) {
        ret = I2C_NACK_DATA;
      } else if (err != HAL_I2C_ERROR_NONE) {
        ret = I2C_ERROR;
      }
    }
  }
  putchar('-');
  putchar('0'+ret);
  return ret;
}
```

上面为复现代码，其中requestFrom的参数quantity=3

### 如果正常，应该是什么样 / Expected behavior

![image](https://github.com/Air-duino/Arduino-AirMCU/assets/20317561/5b693cfa-7d8b-4a6e-87c8-e1415b1fad63)

### 截图 / Screenshots

![image](https://github.com/Air-duino/Arduino-AirMCU/assets/20317561/9935bd75-aebb-4631-bbfa-1facf8e766db)
![image](https://github.com/Air-duino/Arduino-AirMCU/assets/20317561/b83f8652-ce05-4cb3-9aaa-c79d8edd8aa2)

### 日志 / Logs

-

### 系统 / System

Win10 22H2

### PACK包版本 / Version

0.4.1

### 验证

- [X] 检查过该问题，之前没有人提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [x] 已经提供了完整的报错信息、日志、截图，没有经过删减。

**Comment by createskyblue** [comment]
![image](https://github.com/Air-duino/Arduino-AirMCU/assets/20317561/048813b7-ee23-42cc-8e7f-0993074b37c2)

**Comment by HalfSweet** [comment]
能否方便提供一下您目前的主频设置？

**Comment by HalfSweet** [comment]
以及，目前您的iic是接入到什么设备上呢

**Comment by createskyblue** [comment]
> 

HSI 4Mhz  HCLK 4MHz
连接传感器BMP280
在传感器端I2C上拉10K

使用自己阉割的Adafruit_BMP280进行驱动，附上完整的代码
[Adafruit_BMP280_Library.zip](https://github.com/Air-duino/Arduino-AirMCU/files/12375840/Adafruit_BMP280_Library.zip)
[bmp280test.zip](https://github.com/Air-duino/Arduino-AirMCU/files/12375845/bmp280test.zip)

新的测试代码跑出来的波形图应该是这样
![image](https://github.com/Air-duino/Arduino-AirMCU/assets/20317561/1e9fcecd-bd55-4419-b078-d502dac1e0a5)

**Comment by chenxuuu** [comment]
我这里可以复现

```c
#include <Wire.h>


void setup() {
  Serial.begin(9600);
  Wire.setSDA(PF_0);
  Wire.setSCL(PF_1);
  Wire.begin();

  //软复位
  Wire.beginTransmission(0x77);
  Wire.write(0xD0);
  Wire.endTransmission(true);
  Serial.println("sent request");
  Wire.requestFrom(0x77, 1);
  Serial.println("read request");
  Serial.println(Wire.read());
  Serial.println(Wire.read());
  //读A1
  Wire.beginTransmission(0x77);
  Wire.write(0xAA);
  Wire.endTransmission(true);
  Serial.println("sent request");
  Wire.requestFrom(0x77, 2);//卡在这里
  Serial.println("read request");
  Serial.println(Wire.available());
}


void loop() {}
```
