### ISSUE TITLE
希望新增一下用Flash模拟EEPROM的库

### ISSUE THREAD

**Issue by lineleb** [Air-duino/Arduino-AirMCU#58]
### 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.

这款芯片上没有内嵌EEPROM，有一些需要掉电保存的场景无法使用或者需要外挂EEPROM，一个外挂的EEPROM可能就比air001贵了。
所以希望可以用Flash模拟一下EEPROM来实现掉电保存数据的功能。

### 描述您想要的解决方案 / Describe the solution you'd like

希望提供一个库还有示例程序，可以有数据储存和读出的功能。

### 描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way

可以指定一块Flash地址区域作为储存数据的空间，然后向指定的地址存储和读出数据。

### 确认信息

- [X] 检查过该需求，之前没有人提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 这个需求是真实存在的，并且对于本项目来说是必要的
- [X] 我已经提供了该需求的清晰、详细、完整的方案，请按该方案进行实施
- [X] 我认为我提供的信息已经足够，不需要其他人继续完善该需求的其他细节
- [X] 我同意跟进该需求的实施进程，并在适时提供合理的解释与纠正

**Comment by HalfSweet** [comment]
已经提供相应的库
