### ISSUE TITLE
CI的测试脚本中写死了版本号，应当根据发布的版本动态更新

### ISSUE THREAD

**Issue by HalfSweet** [Air-duino/Arduino-AirMCU#61]
### 描述一下这个bug / Describe the bug

CI的测试脚本中写死了版本号，应当根据发布的版本动态更新

### 复现步骤 / To Reproduce

[空]

### 如果正常，应该是什么样 / Expected behavior

应该根据发布的版本号自动更新

### 截图 / Screenshots

![图片](https://github.com/Air-duino/Arduino-AirMCU/assets/60973476/a1791c12-ad09-4145-bbed-7de3bc6d2984)

### 日志 / Logs

[空]

### 系统 / System

Win11 22H2

### PACK包版本 / Version

0.4.5

### 验证

- [X] 检查过该问题，之前没有人提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] 已经提供了完整的报错信息、日志、截图，没有经过删减。

**Comment by chenxuuu** [comment]
这不算bug，因为后面步骤会直接用仓库新代码覆盖掉下载下来的库
