### ISSUE TITLE
关于AirISP 1.2.7.0 在macOS Arm中运行的问题

### ISSUE THREAD

**Issue by ExMikuPro** [Air-duino/Arduino-AirMCU#71]
### 描述一下这个bug / Describe the bug

AirISP 1.27.0版本运行后直接被```kill```

在我准备完成arduino IDE中开发版相关配置后，使用AirISP 1.27.0尝试下载，出现 ```Failed uploading: uploading error: signal: killed``` 错误（详见第一张截图），直接执行开发板内置ISP出现```[1]    25374 killed```问题（详见第二张截图），拉取1.2.6.0版本问题解决，可以正常下载

### 复现步骤 / To Reproduce

环境：
2020年MacBook Air M1版本
macOS 12.6.4
Arduino IDE 2.1.1
AirMCU 0.4.5
AirISP 1.2.7.0

直接进行编译下载或者下载[AirISP-osx-arm64.tar](https://github.com/Air-duino/AirISP/releases/download/1.2.6.0/AirISP-osx-arm64.tar)并运行会出现```killed```结束语

### 如果正常，应该是什么样 / Expected behavior

None

### 截图 / Screenshots

![图像2023-9-22 00 18](https://github.com/Air-duino/Arduino-AirMCU/assets/72144156/8a2a435d-dc57-4f88-a546-304ec11ba9cf)
<img width="842" alt="截屏2023-09-23 03 28 26" src="https://github.com/Air-duino/Arduino-AirMCU/assets/72144156/43589762-5ccf-48d1-809d-ed6f7b70510c">

### 日志 / Logs

None

### 系统 / System

macOS 12.6.4

### PACK包版本 / Version

AirISP-osx-arm64.tar

### 验证

- [X] 检查过该问题，之前没有人提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 提供了最小可复现工程或详细的复现步骤，确保开发者可以复现 / The provided reproduction is a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.
- [X] 已经提供了完整的报错信息、日志、截图，没有经过删减。

**Comment by chenxuuu** [comment]
可以自行编译试试，去掉` -p:PublishSingleFile=true`参数
