### ISSUE TITLE
麻烦新增spi示例应用程序

### ISSUE THREAD

**Issue by ryiot** [Air-duino/Arduino-AirMCU#72]
### 您的功能请求是否与解决某些问题有关？请描述一下。/ Is your feature request related to a problem? Please describe.

麻烦新增spi示例应用程序

### 描述您想要的解决方案 / Describe the solution you'd like

麻烦新增spi示例应用程序

### 描述您想要的详细使用步骤描述 / Describe the solution you'd like to use in what way

麻烦新增spi示例应用程序

### 确认信息

- [X] 检查过该需求，之前没有人提过 / Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] 这个需求是真实存在的，并且对于本项目来说是必要的
- [X] 我已经提供了该需求的清晰、详细、完整的方案，请按该方案进行实施
- [X] 我认为我提供的信息已经足够，不需要其他人继续完善该需求的其他细节
- [X] 我同意跟进该需求的实施进程，并在适时提供合理的解释与纠正

**Comment by chenxuuu** [comment]
直接参考arduino的spi接口即可
