### ISSUE TITLE
一些引脚问题

### ISSUE THREAD

**Issue by Dr-chen137** [Air-duino/Arduino-AirMCU#77]
1.Datasheet上写有一个12位ADC，请问是analogRead的精度设为12位吗？然后有几个引脚可以调用DAC？
2.请问下PWM输出精度有几位？是只有默认的8位还是有更高？然后PWM输出频率范围是多少，调到最高的话，会对芯片运行有什么影响？
3.air001是否还有除001以外的USRT口。包含Serial0在内的USRT引脚，上传程序的时候是否需要断开除下载器外的其它链接
4.air001所链接的下载器，除GND和VCC外，是否有可以精简的口？比如留下GND，VCC，TX，RX。
5.air001如果想持续查看串口，是要一直插着下载器吗？还是有其它方法？
期待您的早日回复，谢谢

**Comment by HalfSweet** [comment]
1. Yes; Air001 does not have a DAC peripheral.
2. For PWM related issues, please refer to the documentation <https://arduino.luatos.com/library/pwm.html>; we suggest you to test the effect on operation.
3. Air001 has 2 UARTs, please refer to the manual <https://air001.cn>; AirMCU doesn't have Serial0, it is customary to start from 1; theoretically, it doesn't need to be disconnected.
4. Before downloading, you need to enter bootloader
5. As long as you can parse the serial port, you can use anything, even an oscilloscope or a bare metal analyzer.

Please use AirMCU's [issue template](https://github.com/Air-duino/Arduino-AirMCU/issues/new/choose) to create issues in the future. Before creating an issue, please read the previous issues, chip manuals, documentation, etc. in detail. If you do not comply, we will take measures including but not limited to direct closure, refusal to answer, or even refuse to allow you to participate in any form of development, etc. Thank you for your understanding.

1. 是的；Air001没有DAC外设
2. PWM 相关问题请参考文档说明<https://arduino.luatos.com/library/pwm.html>；对于运行的影响建议实测
3. Air001拥有 2 个UART，具体请参考手册<https://air001.cn>；AirMCU 没有Serial0，习惯上均从 1 开始；理论上不需要断开
4. 下载之前需要进入 bootloader
5. 只要是你能解析串口，用什么都可以，哪怕是示波器或者裸机分析仪

以后创建问题请使用AirMCU的[issue模板](https://github.com/Air-duino/Arduino-AirMCU/issues/new/choose)，创建之前请详细阅读之前提过的issue、芯片手册、使用文档等。如若不遵守，我们将采取包括但不限于直接关闭、拒绝回答、甚至于拒绝您参与任何形式的开发等措施，感谢您的理解。
