### ISSUE TITLE
在arduino里面是否可以直接操作寄存器，达到直接操作未封装的硬件模块的目的

### ISSUE THREAD

**Issue by wangshujun-tj** [Air-duino/Arduino-AirMCU#87]
这个我理解应该是一个基础的能力，可能已经支持，帮忙给出示例也可以

**Comment by HalfSweet** [comment]
Please use AirMCU's [issue template](https://github.com/Air-duino/Arduino-AirMCU/issues/new/choose) to create issues in the future. Before creating an issue, please read the previous issues, chip manuals, documentation, etc. in detail. If you do not comply, we will take measures including but not limited to direct closure, refusal to answer, or even refuse to allow you to participate in any form of development, etc. Thank you for your understanding.
